language: python
python: 3.6
sudo: true
dist: trusty

cache:
  - pip3: true

before_install:
  - travis_retry sudo add-apt-repository -y ppa:ethereum/ethereum
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install ethereum

install:
  - travis_retry sudo apt-get install solc
  - travis_retry sudo apt-get install libssl-dev
  - travis_retry pip install --upgrade pip
  - travis_retry pip3 install -r requirements.txt

script: 
  - populus compile
  - bash scripts/init_local_chain.sh
  - py.test tests/testnet

notifications:
  email:
    on_success: never
    on_failure: always